services:
  django-docker:
    image: django-docker
    container_name: django-docker
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - static-volume:/app/productionfiles
      - media-volume:/app/media

  postgres:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static-volume:/app/productionfiles
      - media-volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${HOST_CERT_DIR}:${CERT_DIR}
    depends_on:
      - django-docker

volumes:
  db-data:
  static-volume:
  media-volume:
