# Generated by Django 5.2 on 2025-04-27 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 5, 23, 59, 615827, tzinfo=datetime.timezone.utc)),
        ),
    ]
