# Generated by Django 5.2 on 2025-10-04 22:40

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
