# Generated by Django 5.2 on 2025-10-04 23:14

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
