# Generated by Django 5.2 on 2025-10-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_thumb_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rating',
            field=models.CharField(choices=[(0, 'safe'), (1, 'questionable'), (2, 'explicit')], default=(0, 'safe')),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128, unique=True)),
                ('posts', models.ManyToManyField(to='post.post')),
            ],
        ),
    ]
