# Generated by Django 5.2 on 2025-10-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_content_rating_post_tags_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_rating',
            field=models.CharField(choices=[(0, 'safe'), (1, 'questionable'), (2, 'explicit')], default=0),
        ),
    ]
