# Generated by Django 5.2 on 2025-10-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_content_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_rating',
            field=models.IntegerField(choices=[(0, 'safe'), (1, 'questionable'), (2, 'explicit')], default=0),
        ),
    ]
