# Generated by Django 5.2 on 2025-04-27 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_invite_invite_code_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 5, 19, 46, 199562)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(default='r"q1#j,#NN=LjF,,j"zXmup1', unique=True),
        ),
    ]
