# Generated by Django 5.2 on 2025-04-27 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_created_at_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(default='8_r4Zy;O]s6Y4?I.:0ubAelq', unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 5, 23, 59, 615436, tzinfo=datetime.timezone.utc)),
        ),
    ]
