# Generated by Django 5.2 on 2025-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_invite_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(default='zmvpo>}B,kC~*l+Yv6zQw4Ba', unique=True),
        ),
    ]
