# Generated by Django 5.2 on 2025-05-05 18:08

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userprofile_display_name_alter_invite_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(default=user.models.generate_invite_code, unique=True),
        ),
    ]
