# Generated by Django 5.2 on 2025-10-04 23:41

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_invite_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=thumbnails.fields.ImageField(blank=True, default=None, null=True, upload_to='avatars/'),
        ),
    ]
