# Generated by Django 5.2 on 2025-10-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content_preference',
            field=models.IntegerField(choices=[(0, 'safe'), (1, 'questionable'), (2, 'explicit')], default=0),
        ),
    ]
